### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by yilinxia** [yilinxia/rulegoal_graph#2]
- rule to graph
- [ ] add special relationship nodes to the graph, for instance, `!=`,`<`,`>`,`=`,`>=`, `<=`, map to a predicates "ne", "lt", "gt", "eq", "ge", "le", use a different color
- [ ] show variables within the nodes
- rule on graph
- [ ] mark unstratified rules in the graph 
```
q(X,f(X)):- q(_,X).
q(X,f(X)):- q(X,_).
```
